projects:
  sportm-dev:
    schemaPath: amplify/src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 7mljvmanhjhkpfkqigakb2x3fu
        maxDepth: 4
extensions:
  amplify:
    version: 3
